=== dmzoneill/lm051/Semester 3/CS4146 - Document Architectures/lab files/tv.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT tvshow 
(
    title,
    genrelist,
    creator,
    cast
)>
<!ELEMENT title (#PCDATA) >
<!ELEMENT genrelist (genre+) >
<!ELEMENT creator (firstname,surname) >
<!ELEMENT cast (castmember+) >

<!ELEMENT genre (#PCDATA) >

<!ELEMENT firstname (#PCDATA) >
<!ELEMENT surname (#PCDATA) >

<!ELEMENT castmember (firstname, surname) >

<!ATTLIST castmember role CDATA #REQUIRED>
<!ATTLIST tvshow year CDATA #REQUIRED>
<!ATTLIST tvshow rating CDATA #REQUIRED>
<!ATTLIST tvshow season CDATA #REQUIRED>


<!ATTLIST genre name (Animation|SciFi|Comedy) "Animation">

=== dmzoneill/lm051/Semester 3/CS4146 - Document Architectures/lab files/tvshow02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tvshow SYSTEM "tv.dtd">
<tvshow year="1999" rating="PG" season="1">
    <title>Futurama</title>
    <genrelist>
        <genre name="Cartoon"/>
    </genrelist>
    <creator>
        <firstname>Matt</firstname>
        <surname>Groening</surname>
    </creator>
    <cast>
        <castmember role="Philip J. Fry">
            <firstname>Billy</firstname>
            <surname>West</surname>
        </castmember>
    </cast>
</tvshow>

=== dmzoneill/lm051/Semester 3/CS4146 - Document Architectures/lab files/tvshow01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tvshow SYSTEM "tv.dtd">
<tvshow year="1999" rating="PG" season="1">
    <title>Futurama</title>
    <genrelist>
        <genre name="Animation"/>
        <genre name="SciFi"/>
        <genre name="Comedy"/>
    </genrelist>
    <creator>
        <firstname>Matt</firstname>
        <surname>Groening</surname>
    </creator>
    <cast>
        <castmember role="Philip J. Fry">
            <firstname>Billy</firstname>
            <surname>West</surname>
        </castmember>
        <castmember role="Turanga Leela">
            <firstname>Katey</firstname>
            <surname>Sagal</surname>
        </castmember>
    </cast>
</tvshow>
